site_name: Agentic Knowledge Garden
site_description: Public repository for agentic AI knowledge
site_url: https://oldaque.github.io/agentic-knowledge-garden

nav:
  - Home: home.md
  - Guide: guide/README.md
  - Patterns: patterns/README.md
  - Resources: resources/README.md
  - Notes: notes/README.md
  - Snippets: snippets/README.md
  - Examples: examples/README.md


theme:
  name: material
  palette:
    - scheme: slate
  features:
    - navigation.sections
    - content.code.copy

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables

extra_css:
  - assets/extra.css